# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20170928_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='accounts',
        ),
    ]
