# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
