# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_item_popularity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Adminuser',
        ),
    ]
