# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_auto_20170927_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
