# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_auto_20170928_1736'),
        ('ecommerce', '0014_auto_20170928_1114'),
    ]

    operations = [
    ]
