# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_auto_20170929_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IN PROGRESS', 'In Progress'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='PROGRESS', max_length=40)),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Adminuser')),
                ('billing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ecommerce.Billing')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
    ]
