# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_auto_20170929_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_cart', to='ecommerce.Cart'),
        ),
    ]
